// spa/react/src/App.jsx
import { useAuth } from 'react-oidc-context';
import { useState, useEffect, useMemo } from 'react';

// Display only -- never an authorization decision.
//
// This decodes the access token payload WITHOUT verifying its signature. A public
// client gains nothing by verifying a token it just received over TLS from the token
// endpoint, and shipping a JOSE library to the browser to do it would teach the wrong
// lesson. The security decision belongs to the resource server, which must verify the
// signature and the audience -- see mcp/remote-server-ts, or spa/bff-express for a
// backend that holds the tokens instead.
function decodeUnverifiedForDisplay(token) {
  return JSON.parse(atob(token.split('.')[1].replace(/-/g, '+').replace(/_/g, '/')));
}

function TokenInfo({ auth }) {
  const [timeLeft, setTimeLeft] = useState(null);

  useEffect(() => {
    if (!auth.user?.expires_at) return;

    function update() {
      const seconds = auth.user.expires_at - Math.floor(Date.now() / 1000);
      setTimeLeft(seconds > 0 ? seconds : 0);
    }

    update();
    const interval = setInterval(update, 1000);
    return () => clearInterval(interval);
  }, [auth.user?.expires_at]);

  if (timeLeft === null) return null;

  return (
    <div style={{ marginTop: '1rem', padding: '1rem', background: '#f5f5f5', borderRadius: '4px' }}>
      <h3>Token Info</h3>
      <p>Token expires in: <strong>{timeLeft}s</strong></p>
    </div>
  );
}

function UserProfile({ auth }) {
  const profile = auth.user?.profile;
  const atClaims = useMemo(
    () => auth.user?.access_token ? decodeUnverifiedForDisplay(auth.user.access_token) : {},
    [auth.user?.access_token],
  );
  if (!profile) return null;

  return (
    <div style={{ marginTop: '1rem', padding: '1rem', background: '#f0f8ff', borderRadius: '4px' }}>
      <h3>Profile Claims</h3>
      <ul style={{ listStyle: 'none', padding: 0 }}>
        <li><strong>sub:</strong> {profile.sub}</li>
        <li><strong>email:</strong> {profile.email}</li>
        {profile.email_verified !== undefined && (
          <li><strong>email_verified:</strong> {String(profile.email_verified)}</li>
        )}
        <li><strong>hardware_verified:</strong> {String(atClaims.hardware_verified || false)}</li>
        {atClaims.acr && <li><strong>acr:</strong> {atClaims.acr}</li>}
        {atClaims.amr && <li><strong>amr:</strong> {atClaims.amr.join(', ')}</li>}
        {atClaims.cnf?.jkt && <li><strong>DPoP-bound (cnf.jkt):</strong> {atClaims.cnf.jkt}</li>}
      </ul>
    </div>
  );
}

export default function App() {
  const auth = useAuth();

  // isAuthenticated is only computed when the user loads, so drop the user when the
  // token expires rather than keep showing "Signed in" with a dead token.
  useEffect(() => auth.events.addAccessTokenExpired(() => auth.removeUser()), [auth.events, auth.removeUser]);

  if (auth.isLoading) {
    return (
      <div style={{ fontFamily: 'system-ui', padding: '2rem' }}>
        <h1>Vouch OIDC + React SPA</h1>
        <p>Loading...</p>
      </div>
    );
  }

  if (auth.error) {
    return (
      <div style={{ fontFamily: 'system-ui', padding: '2rem' }}>
        <h1>Vouch OIDC + React SPA</h1>
        <p>Error: {auth.error.message}</p>
      </div>
    );
  }

  return (
    <div style={{ fontFamily: 'system-ui', padding: '2rem' }}>
      <h1>Vouch OIDC + React SPA</h1>
      {auth.isAuthenticated && !auth.user?.expired ? (
        <div>
          <p>Signed in as {auth.user?.profile.email}</p>
          {auth.user?.access_token && decodeUnverifiedForDisplay(auth.user.access_token).hardware_verified && (
            <p><strong>Hardware Verified</strong></p>
          )}
          <UserProfile auth={auth} />
          <TokenInfo auth={auth} />
          <div style={{ marginTop: '1rem' }}>
            {/*
              signoutRedirect, not removeUser. removeUser only clears local storage,
              which leaves the Vouch session intact -- the next sign-in completes
              silently and looks like the sign-out never happened. It also made the
              post_logout_redirect_uri configured in main.jsx dead config, since
              nothing ever reached the end_session endpoint.
            */}
            <button onClick={() => auth.signoutRedirect()}>Sign out</button>
          </div>
        </div>
      ) : (
        <button onClick={() => auth.signinRedirect()}>Sign in with Vouch</button>
      )}
    </div>
  );
}

// spa/angular/src/app/app.component.ts
import { Component, OnDestroy, OnInit, computed, signal } from '@angular/core';
import { RouterOutlet } from '@angular/router';
import type { User } from 'oidc-client-ts';
import { getUser, userManager } from './auth';

// Display only -- never an authorization decision.
//
// This decodes the access token payload WITHOUT verifying its signature. A public
// client gains nothing by verifying a token it just received over TLS from the token
// endpoint, and shipping a JOSE library to the browser to do it would teach the wrong
// lesson. The security decision belongs to the resource server, which must verify the
// signature and the audience -- see mcp/remote-server-ts, or spa/bff-express for a
// backend that holds the tokens instead.
function decodeUnverifiedForDisplay(token: string): Record<string, unknown> {
  return JSON.parse(atob(token.split('.')[1].replace(/-/g, '+').replace(/_/g, '/')));
}

@Component({
  selector: 'app-root',
  standalone: true,
  imports: [RouterOutlet],
  template: `
    <div style="font-family: system-ui; padding: 2rem">
      <h1>Vouch OIDC + Angular SPA</h1>

      @if (user(); as user) {
        <p>Signed in as {{ user.profile.email }}</p>
        @if (atClaims()['hardware_verified']) {
          <p><strong>Hardware Verified</strong></p>
        }
        <div style="margin-top: 1rem; padding: 1rem; background: #f0f8ff; border-radius: 4px">
          <h3>Profile Claims</h3>
          <ul style="list-style: none; padding: 0">
            <li><strong>sub:</strong> {{ user.profile.sub }}</li>
            <li><strong>email:</strong> {{ user.profile.email }}</li>
            @if (user.profile.email_verified !== undefined) {
              <li><strong>email_verified:</strong> {{ user.profile.email_verified }}</li>
            }
            <li><strong>hardware_verified:</strong> {{ atClaims()['hardware_verified'] || false }}</li>
            @if (atClaims()['acr']) {
              <li><strong>acr:</strong> {{ atClaims()['acr'] }}</li>
            }
            @if (amr().length) {
              <li><strong>amr:</strong> {{ amr().join(', ') }}</li>
            }
            @if (jkt()) {
              <li><strong>DPoP-bound (cnf.jkt):</strong> {{ jkt() }}</li>
            }
          </ul>
        </div>
        <div style="margin-top: 1rem; padding: 1rem; background: #f5f5f5; border-radius: 4px">
          <h3>Token Info</h3>
          <p>Token expires in: <strong>{{ timeLeft() }}s</strong></p>
        </div>
        <div style="margin-top: 1rem">
          <button (click)="logout()">Sign out</button>
        </div>
      } @else {
        <button (click)="login()">Sign in with Vouch</button>
      }

      <router-outlet></router-outlet>
    </div>
  `,
})
export class AppComponent implements OnInit, OnDestroy {
  private timer?: ReturnType<typeof setInterval>;
  private now = signal(Math.floor(Date.now() / 1000));

  user = signal<User | null>(null);
  atClaims = computed<Record<string, unknown>>(() => {
    const token = this.user()?.access_token;
    return token ? decodeUnverifiedForDisplay(token) : {};
  });
  amr = computed(() => (this.atClaims()['amr'] as string[] | undefined) ?? []);
  jkt = computed(() => (this.atClaims()['cnf'] as { jkt?: string } | undefined)?.jkt);
  timeLeft = computed(() => Math.max((this.user()?.expires_at ?? 0) - this.now(), 0));

  private onUserLoaded = (user: User) => this.user.set(user);
  private onExpired = async () => {
    await userManager.removeUser();
    this.user.set(null);
  };

  async ngOnInit() {
    // The callback route signs in after this component has loaded, so pick the user
    // up from the event rather than only on startup.
    userManager.events.addUserLoaded(this.onUserLoaded);
    userManager.events.addAccessTokenExpired(this.onExpired);
    this.timer = setInterval(() => this.now.set(Math.floor(Date.now() / 1000)), 1000);
    this.user.set(await getUser());
  }

  ngOnDestroy() {
    userManager.events.removeUserLoaded(this.onUserLoaded);
    userManager.events.removeAccessTokenExpired(this.onExpired);
    clearInterval(this.timer);
  }

  login() {
    userManager.signinRedirect();
  }

  // signoutRedirect, not removeUser: removeUser only clears local storage and leaves
  // the Vouch session intact, so the next sign-in completes silently.
  logout() {
    userManager.signoutRedirect();
  }
}
