// spa/react/src/Callback.jsx
import { useAuth } from 'react-oidc-context';
import { useEffect } from 'react';
import { useNavigate } from 'react-router';

export default function Callback() {
  const auth = useAuth();
  const navigate = useNavigate();

  useEffect(() => {
    if (!auth.isLoading && auth.isAuthenticated) {
      navigate('/');
    }
  }, [auth.isLoading, auth.isAuthenticated, navigate]);

  return (
    <div style={{ fontFamily: 'system-ui', padding: '2rem' }}>
      {auth.error ? (
        <p>Login failed: {auth.error.message}. <a href="/">Try again</a></p>
      ) : (
        <p>Processing login...</p>
      )}
    </div>
  );
}

// spa/vue/src/Callback.vue
<script setup>
import { ref, onMounted } from 'vue';
import { useRouter } from 'vue-router';
import { handleCallback } from './auth';

const router = useRouter();
const error = ref(null);

onMounted(async () => {
  try {
    await handleCallback();
    router.push('/');
  } catch (err) {
    console.error('Login error:', err);
    error.value = err.message;
  }
});
</script>

<template>
  <p v-if="error">Login failed: {{ error }}. <a href="/">Try again</a></p>
  <p v-else>Processing login...</p>
</template>
