// spa/vue/src/Callback.vue
<script setup>
import { ref, onMounted } from 'vue';
import { useRouter } from 'vue-router';
import { handleCallback } from './auth';

const router = useRouter();
const error = ref(null);

onMounted(async () => {
  try {
    await handleCallback();
    router.push('/');
  } catch (err) {
    console.error('Login error:', err);
    error.value = err.message;
  }
});
</script>

<template>
  <p v-if="error">Login failed: {{ error }}. <a href="/">Try again</a></p>
  <p v-else>Processing login...</p>
</template>

// spa/sveltekit/src/routes/callback/+page.svelte
<script>
  import { onMount } from 'svelte';
  import { goto } from '$app/navigation';
  import { handleCallback } from '$lib/auth';

  let error = $state(null);

  onMount(async () => {
    try {
      await handleCallback();
      goto('/');
    } catch (err) {
      console.error('Login error:', err);
      error = err.message;
    }
  });
</script>

{#if error}
  <p>Login failed: {error}. <a href="/">Try again</a></p>
{:else}
  <p>Processing login...</p>
{/if}
